### ISSUE TITLE
Does nothing?

### ISSUE THREAD

**Issue by xparq** [sanemat/example-e-residency#5]
Hi there, I searched e-Res. and found your repo, gave it a try, but the buttons seem to do nothing (no error messages, no changes I could see), irrespective of having the ID card inserted or not.

How to properly test it, actually?

Thanks!

**Comment by sanemat** [comment]
This repository is still "work in progress". Would you read https://github.com/hwcrypto/hwcrypto.js and try demo directory?

**Comment by xparq** [comment]
Sorry, I didn't notice your answer, I get too much noise from GitHub.
